#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-nexus-maven-plugins
Version  : 1.6.3
Release  : 2
URL      : https://repo1.maven.org/maven2/org/sonatype/nexus/maven/nexus-common/1.6.3/nexus-common-1.6.3.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/nexus/maven/nexus-common/1.6.3/nexus-common-1.6.3.jar
Source1  : https://repo1.maven.org/maven2/org/sonatype/nexus/maven/nexus-common/1.6.3/nexus-common-1.6.3.pom
Source2  : https://repo1.maven.org/maven2/org/sonatype/nexus/maven/nexus-maven-plugins/1.6.3/nexus-maven-plugins-1.6.3.pom
Source3  : https://repo1.maven.org/maven2/org/sonatype/nexus/maven/nexus-staging/1.6.3/nexus-staging-1.6.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : EPL-1.0
Requires: mvn-nexus-maven-plugins-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-nexus-maven-plugins package.
Group: Data

%description data
data components for the mvn-nexus-maven-plugins package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-common/1.6.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-common/1.6.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-common/1.6.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-common/1.6.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-maven-plugins/1.6.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-maven-plugins/1.6.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-staging/1.6.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-staging/1.6.3


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-common/1.6.3/nexus-common-1.6.3.jar
/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-common/1.6.3/nexus-common-1.6.3.pom
/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-maven-plugins/1.6.3/nexus-maven-plugins-1.6.3.pom
/usr/share/java/.m2/repository/org/sonatype/nexus/maven/nexus-staging/1.6.3/nexus-staging-1.6.3.pom
